#!/bin/sh /etc/rc.common

# enables the correct bitbanged spi device 

START=60

start() {
	. /lib/ar71xx.sh 
	case $(ar71xx_board_name) in
	yun)
		insmod spi-gpio-custom bus0=1,11,27,8,0,125000
		;;
	nuy)
		insmod spi-gpio-custom bus0=1,19,20,21,0,125000
		;;
	esac
}
